class ProvisoryAutenticatorToken {
  static String token =
      'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyYzE5ODY4NzdmMmQxZTNiYjRmNjdiNTNjNzFmMzE2NiIsInN1YiI6IjYyZTlhODNmMzAzYzg1MDA1ZDIzYjk1ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.YS9d2q3AMiyDWVCM_gF-KhaKwfOR2wzoUC8Vngmh39E';
}
